### ISSUE TITLE
Iris data: The A and B dimensions do not match

### ISSUE THREAD

**Issue by cgearhart** [cgearhart/students-filters#2]
Performing ICA on the iris data returns a matrix dimension mismatch error.

**Comment by lichard49** [comment]
Hi, what does this error mean in general?  I'm getting this issue on my own data set (not the Iris one).

**Comment by cgearhart** [comment]
This patch fixed the ICA filter to ignore the data type of the class attribute. Iris dataset has multi-valued nominal attribute class label; this ICA implementation does not support nominal attributes in the input data.

WEKA GUI sometimes produces cryptic error message "Problem filtering instances: The 'a' and 'b' matrices do not have compatible dimensions", or the more reasonable "All data must be numeric". It can be more useful for debugging to invoke the filter from the command line to generate a more detailed stack trace.

*Adding stack trace from command line for posterity:*
```
weka.core.UnsupportedAttributeTypeException: weka.filters.unsupervised.attribute.IndependentComponents: Cannot handle multi-valued nominal attributes!
	at weka.core.Capabilities.test(Capabilities.java:940)
	at weka.core.Capabilities.test(Capabilities.java:868)
	at weka.core.Capabilities.test(Capabilities.java:1084)
	at weka.core.Capabilities.test(Capabilities.java:1022)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
	at weka.filters.Filter.testInputFormat(Filter.java:446)
	at weka.filters.Filter.setInputFormat(Filter.java:464)
	at weka.filters.unsupervised.attribute.IndependentComponents.setInputFormat(IndependentComponents.java:325)
	at weka.filters.Filter.filterFile(Filter.java:1069)
	at weka.filters.Filter.runFilter(Filter.java:1340)
	at weka.filters.unsupervised.attribute.IndependentComponents.main(IndependentComponents.java:473)
```
